### ISSUE TITLE
Clickable topic tags on the Symposium page don't work

### ISSUE THREAD

**Issue by katherinehebert** [QCBSRworkshops/QCBSRworkshops.github.io#2]
The clickable topic tags on the Symposium page don't select the relevant workshop pages. All workshops disappear when a tag is clicked.

**Comment by pedrohbraga** [comment]
Hi, @katherinehebert! Thank you for this! I am aware of the issue. It happens because more than one category is being attributed to the YAML `category` tag.

I have briefly been to the theme code that relates to this, but I was unable to fix it. I will let the theme authors know about this, so we hopefully can apply the categories in both workshop sections.

**Comment by pedrohbraga** [comment]
I opened issue [#177](https://github.com/themefisher/airspace-hugo/issues/177#issue-908738487) within [themefisher/airspace-hugo](https://github.com/themefisher/airspace-hugo).

The contributors followed up with the pull-request [#178](https://github.com/themefisher/airspace-hugo/pull/178#issue-660081177).

I will wait for their merge before bringing the changes to `layouts/project/list.html`.

For the moment, there is no need to change the categories you included on the symposium page.

**Comment by pedrohbraga** [comment]
The issue has been fixed with [7ae5eab](https://github.com/QCBSRworkshops/QCBSRworkshops.github.io/commit/7ae5eab841ccfc0b76a11c4b61efb2364a543712).
